travis:
  secure:
    BINSTAR_TOKEN: hGeCencAxU8WDXkxy3owGzLA/wW+SCnl468x13bi6yKYFbvt/eWa7RcyLidSwr0/rx8QFStDrU5VSVy5ciLHYo+Y51B4aXJqglWbU6bw8b5lEktxDGeOYpMWU2JepVHct27yWv4LVcN1LY9pkHiPg0uj0cOSfQeCXKY6UYHbMshnDYN661Vu0Coj0BjVhd2jrpk5uakMuRHoI0QCwznsNOMJd0t6c8yJrZcHkfJVrdh113ChAPYttiJDD5hS+CBnhrU1AddfTsq/Fx3JoXnrEJIdzZSLwxA8zxIJIO95iqEYlc3bLKF1KmXPeZ6yV2QxNHx/JA8LVX8/craIVPgvo1Oso3q2ceqlwlN2SMvQOrow2MRlBe6qn8DLRPta1ICLhvE/QFdCxbFIX/DzqwFDy9LfpQwLi8QyNw5ffXDSM02KOdNm23p994PIuIPevxph8RnYvLhNaK3Bfidjr51kwpwroX6ShKCdobCUO9YkmFlDvLkp4YD1SfdVOFKB3hT/JkvKyFT9hYWa+WCmcY5RzJUjJXdLH9M4sdAw/HKU8LPRKx8qYp2Q67vbFMAIZVzlf9LljzLp+aE81nEWOf5zSJqfPkrPyakXeuB5BODvCh03ZPGjk1Xo2ODb67GLTPbJFPvbbpIKassVjaJ66DHp+0j/AEDNqZLLpy5dufs9l3E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
